### PR TITLE
feat(extra): Update wezterm with retro tab

### PR DESCRIPTION
**Pull request by EdenEast**
Screen Shot 2022-08-07 at 8 18 06 PM

Resolves: #191

### CODE REVIEW

**Comment by gegoune** [comment]
Tried with
```lua
  color_scheme_dirs = { wezterm.home_dir .. '/.local/share/nvim/site/pack/packer/start/nightfox.nvim/extra/nightfox' },
  color_scheme = 'nightfox_wezterm',
```
But no colours get applied at all. Probably not the way to test it out, but looks good from the screenshot.

**Comment by EdenEast** [comment]
Ya I could not get that working as well. I had to apply the colors through the colors table to get something that I could see. Also renaming to arst for both the filename and name in the file did not work either.

**Comment by wez** [comment]
There are error(s) in the toml files. I think you should be able to see these in wezterm, after trying to load them, if you press `CTRL-SHIFT-L` to pop open the debug console.

These errors are emitted by my sync machinery:

```
[2022-08-08T13:51:40Z ERROR sync_color_schemes] https://github.com/EdenEast/nightfox.nvim/tarball/main/EdenEast-nightfox.nvim-631abad/extra/dawnfox/nightfox_wezterm.toml: Error processing colors.tab_bar.active_tab.bg_color (types: ColorSchemeFile, Palette, TabBarColors, TabBarColor) missing field `bg_color`
[2022-08-08T13:51:40Z ERROR sync_color_schemes] https://github.com/EdenEast/nightfox.nvim/tarball/main/EdenEast-nightfox.nvim-631abad/extra/dayfox/nightfox_wezterm.toml: Error processing colors.tab_bar.active_tab.bg_color (types: ColorSchemeFile, Palette, TabBarColors, TabBarColor) missing field `bg_color`
[2022-08-08T13:51:40Z ERROR sync_color_schemes] https://github.com/EdenEast/nightfox.nvim/tarball/main/EdenEast-nightfox.nvim-631abad/extra/duskfox/nightfox_wezterm.toml: Error processing colors.tab_bar.active_tab.bg_color (types: ColorSchemeFile, Palette, TabBarColors, TabBarColor) missing field `bg_color`
[2022-08-08T13:51:40Z ERROR sync_color_schemes] https://github.com/EdenEast/nightfox.nvim/tarball/main/EdenEast-nightfox.nvim-631abad/extra/nightfox/nightfox_wezterm.toml: Error processing colors.tab_bar.active_tab.bg_color (types: ColorSchemeFile, Palette, TabBarColors, TabBarColor) missing field `bg_color`
[2022-08-08T13:51:40Z ERROR sync_color_schemes] https://github.com/EdenEast/nightfox.nvim/tarball/main/EdenEast-nightfox.nvim-631abad/extra/nordfox/nightfox_wezterm.toml: Error processing colors.tab_bar.active_tab.bg_color (types: ColorSchemeFile, Palette, TabBarColors, TabBarColor) missing field `bg_color`
[2022-08-08T13:51:40Z ERROR sync_color_schemes] https://github.com/EdenEast/nightfox.nvim/tarball/main/EdenEast-nightfox.nvim-631abad/extra/terafox/nightfox_wezterm.toml: Error processing colors.tab_bar.active_tab.bg_color (types: ColorSchemeFile, Palette, TabBarColors, TabBarColor) missing field `bg_color`
```

**Comment by EdenEast** [comment]
Issues are now resolved.

**Pull request merged**
