### PR TITLE
feat(compiler): add `blend` option for neovim compiler

### PR DESCRIPTION
**Pull request by EdenEast**
Resolves: #293

### CODE REVIEW

**Comment by EdenEast** [comment]
@dmitrii-galantsev I implemented adding `blend` key for neovim's compiler. Do you have a minimal example of actually using this? I have not been able to get an example of this actually working.

**Comment by dmitrii-galantsev** [comment]
I assume you meant to mention @danilax999 ? (I do use nightfox myself, but I'm very confused how I got mentioned)

**Comment by EdenEast** [comment]
Ah yes sorry I got selected the wrong @ user in my dropdown sorry about that...

**Comment by danilax999** [comment]
I've checked this out, and it works now, but I noticed that when you create a new floating window, it uses winblend option, but the telescope window does not. As I already mentioned it works only with highlight-blend. I don't know why, but with default colorschemes and catppuccin it works without highlight-blend. This is probably already another issue.

**Comment by EdenEast** [comment]
I found that there is an issue with linking `NormalNC` to `Normal`. Can you update to the latest change ([773fd0](https://github.com/EdenEast/nightfox.nvim/commit/773fd00919fdd737569906948a9a527fd0127465)) and see if that fixes the issue with setting telsecope's winblend option.

**Comment by danilax999** [comment]
It works, thank you!

**Comment by EdenEast** [comment]
Np that explains some weird behaviours that was on nightfox but not others like `catppuccin` and `tokyonight`.

**Pull request closed without merging**
