### PR TITLE
✨ Add nordfox and palefox as individual colorschemes

### PR DESCRIPTION
**Pull request by metalelf0**
This allows `:colorscheme nordfox` and `:colorscheme palefox`.

### CODE REVIEW

**Comment by EdenEast** [comment]
Thanks for the PR. I was hesitant of making this change when I made `.load()` be table to take a variant. The issue is that the colorscheme `nightfox` will take the configuration into account when picking the colors to use, but the other two `nordfox` and `palefox` will not. Also for other integrations like lualine, and lightline they would not be the same colors. A colorscheme like [Catppuccino.nvim](https://github.com/Pocco81/Catppuccino.nvim) recently added all the colorschemes accessible with this, but the colorscheme name and the variant names are different. The default is dark_catppuccino where the colorscheme's name just Catppuccino. Nightfox is the name of the colorscheme  && a color variant.

**Comment by metalelf0** [comment]
Hmm, I'm not sure I'm following you. Don't lualine and similar use `g:colors_name`? With my PR, using `:colorscheme nordfox` would still set `g:colors_name` to `nightfox`, so it should work exactly as before the PR.

**Comment by EdenEast** [comment]
I can elaborate using `lualine` as an example. 

```lua
require('lualine').setup {
  options = {
    -- ... your lualine config
    theme = "nightfox"
  }
}
```

Refering to lualine's [contributing] page you can extend lualine's themes by creating a lua file in the path `lua/lualine/themes/<name>.lua`. For `nightfox` [this][example] would be the file sourced when a user sets the theme as `nightfox`. This file gets the color values from the colorcheme [load] function which loads based on the theme in the config.

 The default theme for lualine is `gruvbox` if no theme is set or there is an error loading the theme. This is the same kind of idea for other bars like lightline.

[contributing]: https://github.com/hoob3rt/lualine.nvim/blob/master/CONTRIBUTING.md
[example]: https://github.com/EdenEast/nightfox.nvim/blob/main/lua/lualine/themes/nightfox.lua
[load]: https://github.com/EdenEast/nightfox.nvim/blob/1d423fa/lua/nightfox/colors/init.lua#L30-L48

**Comment by metalelf0** [comment]
Ok. So the difference is between the `require('nightfox').load('nordfox')` syntax and the other:

```
local nightfox = require('nightfox')
nightfox.setup({
  fox = "nordfox",
  -- et cetera
})
nightfox.load()
```

If I used the second syntax in the three individual colorscheme files, would it be ok?

**Comment by EdenEast** [comment]
Yes setting the configuration value and then loading would be a valid solution to the status line issue. This would have to be documented saying that setting the colorscheme the vim way will set the variant. Also have to verify that setting setup multiple times will override the configuration correctly.

**Comment by EdenEast** [comment]
I have been using these changes in my config for a couple of days. I like this approach better then using the load override. I will merge this PR once I figure out changes to the readme.

**Comment by EdenEast** [comment]
Thanks for contributing! You PR is merged.

**Pull request merged**
