### PR TITLE
feat(extras): Added support for ghostty

### PR DESCRIPTION
**Pull request by ethanholz**
Adds support for @mitchellh's Ghostty terminal emulator.

### CODE REVIEW

**Comment by EdenEast** [comment]
Since the ghosttly terminal is still close source and not released I cannot confirm that these are correct. Do you have access to the beta and can confirm that these are correct?

**Comment by ethanholz** [comment]
I do have access to the beta and I can confirm that these themes work. Prior to this, I modified the kitty terafox theme (you can find it here: https://github.com/ethanholz/nix-config/blob/main/ghostty/config) and previously carbonfox to work with these.

**Comment by mitchellh** [comment]
@EdenEast If you're interested, I'd be happy to add you to the beta. Anyone who maintains anything in an ecosystem around terminal emulators (themes included) is an instant invite. No pressure, just wanted to offer. Join the discord and ping me and I'll add you: https://discord.gg/ghostty

**Comment by EdenEast** [comment]
Thanks for contributing. I looked at the extra generation and did some refactors, as I have not touched it in a while. I tried your Pr in ghostty and tested the changes. I will rebase your pr on the refactor that I did and merge this. Thanks for contributing and thanks @mitchellh for letting me try ghostty. Using it as my full time terminal with no issues. Feel the difference between my old terminal `wezterm`.

**Comment by ethanholz** [comment]
Excellent! I appreciate you taking the time to test this, thanks to @mitchellh for providing access to the beta!

**Pull request closed without merging**
