### PR TITLE
Add bufferline support

### PR DESCRIPTION
**Pull request by mehalter**
I have been using bufferline recently and wanted to provide a default theme that can be easily used with it. Here is a screenshot as well:
2022-04-04_10:36:36_screenshot

### CODE REVIEW

**Comment by mehalter** [comment]
Hm looks like my PR has a `stylua` issue in `./lua/nightfox/util/template.lua`. I am not modifying this file in this PR. Should I go ahead and fix the stylua issue?

**Comment by mehalter** [comment]
Ah nice catch, I forgot stylua is disabled for that section

**Comment by EdenEast** [comment]
Ya I was doing that because I found that easier to read when I aligned the sections to read what the fg and bg are.

**Comment by EdenEast** [comment]
LGTM

**Pull request merged**
